name: New Relic - AWS Logs Ingestion - Release

on:
  release:
    types: [released]

jobs:
  release:
    strategy:
      matrix:
        python-version: ["3.9"]
        poetry-version: ["1.4"]
        os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install Project
        run: poetry install --no-interaction
      - name: Test
        run: poetry run pytest
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_SAR_PUBLISHER_ROLE }}
          aws-region: us-east-1
      - name: Build & Package & Publish
        command: |
          poetry export -o src/requirements.txt --without-hashes
          poetry run sam validate
          poetry run sam build
          poetry run sam package --s3-bucket nr-serverless-applications --output-template-file packaged.yaml
          poetry run sam publish --region us-east-1 --template packaged.yaml


